# Generated by Django 4.2.3 on 2023-08-10 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_comment_posted_by_alter_comment_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='posted_by',
            field=models.CharField(max_length=100),
        ),
    ]
